package types

import (
	sdk "github.com/cosmos/cosmos-sdk/types"
)

type MappedAddress struct {
	Address Address `json:"address"`
}

type Address struct {
	Network string `json:"network"`
	Label   string `json:"label"`
	Value   string `json:"value"`
	Creator string `json:"creator"`
}

type NestedData struct {
	Events []NftTransferEvent `json:"events"`
}

type Data struct {
	NestedData NestedData `json:"action_nft_transfer_events"`
}

type NftTransferHistory struct {
	Data Data `json:"data"`
}

type TxResponse struct {
	Timestamp    string `json:"timestamp"`
	TimestampInt int64
	Events       []sdk.Event `json:"events"`
}

type TxQueryResponse struct {
	TxResponses []TxResponse `json:"tx_responses"`
	Pagination  struct {
		NextKey interface{} `json:"next_key"`
	} `json:"pagination"`
}

type NftTransferEvent struct {
	DenomId   string `json:"denom_id"`
	TokenId   string `json:"token_id"`
	To        string `json:"to"`
	From      string `json:"from"`
	Timestamp int64  `json:"timestamp"`
}

// Generated by https://quicktype.io

// type NftTransferHistory struct {
// 	Data NftTransferHistoryData `json:"data"`
// }

// type NftTransferHistoryData struct {
// 	ActionNftTransferEvents NftTransferHistoryActions `json:"action_nft_transfer_events"`
// }

// type NftTransferHistoryActions struct {
// 	Events []NftTransferHistoryEvent `json:"events"`
// }

type FarmHashRate []FarmHashRateElement

type FarmHashRateElement struct {
	Time             string  `json:"time"`
	UnixTime         int64   `json:"unixTime"`
	AverageWorkers   float64 `json:"averageWorkers"`
	HashrateAccepted float64 `json:"hashrateAccepted"`
	HashrateStale    int64   `json:"hashrateStale"`
	HashrateRejected int64   `json:"hashrateRejected"`
}

type CollectionResponse struct {
	Height string           `json:"height"`
	Result CollectionResult `json:"result"`
}

type CollectionResult struct {
	Collections []Collection `json:"collections"`
}

type DenomsByDataProperty struct {
	Id       string             `json:"id"`
	DataJson DataJsonCollection `json:"data_json"`
}

type CData struct {
	DenomsByDataProperty []DenomsByDataProperty `json:"denoms_by_data_property"`
}

type CollectionData struct {
	Data CData `json:"data"`
}

type DataJsonCollection struct { // hasura response
	FarmId string `json:"farm_id"`
	Owner  string `json:"owner"`
}
