version: '3.6'
services:
  aura-pay:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      HASURA_URL: ${HASURA_URL}
      NODE_REST_URL: ${NODE_REST_URL}
      BITCOIN_NODE_URL: ${BITCOIN_NODE_URL}
      BITCOIN_NODE_PORT: ${BITCOIN_NODE_PORT}
      BITCOIN_NODE_USER_NAME: ${BITCOIN_NODE_USER_NAME}
      BITCOIN_NODE_PASSWORD: ${BITCOIN_NODE_PASSWORD}
      FOUNDRY_POOL_API_BASE_URL: ${FOUNDRY_POOL_API_BASE_URL}
      FOUNDRY_POOL_API_KEY: ${FOUNDRY_POOL_API_KEY}
      DB_DRIVER_NAME: ${DB_DRIVER_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      AURA_POOL_BACKEND_URL: ${AURA_POOL_BACKEND_URL}
      IS_TESTING: ${IS_TESTING}
      NETWORK: ${NETWORK}
      CUDO_MAINTENANCE_FEE_PERCENT: ${CUDO_MAINTENANCE_FEE_PERCENT}
      CUDO_MAINTENANCE_FEE_PAYOUT_ADDRESS: ${CUDO_MAINTENANCE_FEE_PAYOUT_ADDRESS}
      AURA_POOL_TEST_FARM_WALLET_PASSWORD: ${AURA_POOL_TEST_FARM_WALLET_PASSWORD}
    logging:
      driver: "json-file"
      options:
        max-size: "128m"
        max-file: "1"



